# Generated by Django 4.1.3 on 2022-11-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['address']},
        ),
    ]
